name: CI - Run Tests Only

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout kode dari repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js (versi yang sesuai proyek Anda)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Jalankan test (tanpa build)
      - name: Run Tests
        run: npm test -- --coverage